In [24]:
# Seeing results of the SummaryTMP
import pandas as pd

df = pd.read_csv('TMP_results/summary/summary_result.csv')
errs=len(df[df['decision']=='ERROR'])
print(f'Number of errors: {errs}')
uniques=df['thermal_range'].unique()
print(f'Unique entries: {uniques}')
df[df['thermal_range']=='psychrophile']

Number of errors: 14
Unique entries: ['mesophile' 'psychrophile' 'ERROR' 'thermophile']

,model,accession,phage,metadata,host,taxonomic_level,host_reasoning,host_confidence,host_source,host_found,...,decision,nodes,timings,JSONDecodeError,summary_file,relevant_accession_papers,relevant_accession_dir_size,relevant_host_papers,relevant_host_dir_size,error_message
3,gemma4:e4b,YCQ78089,Shewanella phage Persephone,"{""uid"": ""3153849337"", ""accession"": ""YCQ78089"",...",Shewanella oneidensis MR-1,strain,The metadata explicitly lists the 'host' as 'S...,NaN,metadata,True,...,end,"[""CreateAccessionLibrary"", ""ClassifyHostMetada...","{""CreateAccessionLibrary"": 22.18, ""ClassifyHos...",False,TMP_results/accessions/YCQ78089/summary/summar...,"['PMC3446801.1.txt', 'PMC10820777.1.txt']",2,"['PMC13066108.1.txt', 'PMC13021941.1.txt', '42...",9,NaN
15,gemma4:e4b,YCB25778,Escherichia phage vB_EcoA_8D1,"{""uid"": ""3131198239"", ""accession"": ""YCB25778"",...",Escherichia coli,species,The metadata explicitly contains the key 'host...,NaN,metadata,True,...,end,"[""CreateAccessionLibrary"", ""ClassifyHostMetada...","{""CreateAccessionLibrary"": 3.04, ""ClassifyHost...",False,TMP_results/accessions/YCB25778/summary/summar...,[],0,"['PMC13163687.1.txt', 'PMC13162333.1.txt', 'PM...",6,NaN
31,gemma4:e4b,XYS98208,Escherichia phage CCU7,"{""uid"": ""3040683829"", ""accession"": ""XYS98208"",...",Escherichia coli,species,The metadata explicitly states the 'host' fiel...,NaN,metadata,True,...,end,"[""CreateAccessionLibrary"", ""ClassifyHostMetada...","{""CreateAccessionLibrary"": 5.06, ""ClassifyHost...",False,TMP_results/accessions/XYS98208/summary/summar...,[],0,"['PMC13163687.1.txt', 'PMC13162333.1.txt', 'PM...",6,NaN

In [25]:
df =pd.read_csv('TMP_results/fast/fast_result.csv')
errs=len(df[df['decision']=='ERROR'])
print(f'Number of errors: {errs}')
uniques=df['thermal_range'].unique()
print(f'Unique entries: {uniques}')
df[df['thermal_range']=='psychrophile']

Number of errors: 244
Unique entries: ['mesophile' '2010-2020' '2018-2023' 'thermophile' '2023-2024' 'ERROR' nan
 '1999-2014' 'psychrophile' '1990-2020' '2000-2024']

,model,accession,phage,metadata,host,taxonomic_level,host_reasoning,host_confidence,host_source,host_found,...,duration,decision,nodes,timings,JSONDecodeError,thermal_source,inference_type,host_paper,thermal_paper,error_message
425,gemma4:e4b,YP_009213881,Escherichia phage vB_EcoM_VR26,"{""uid"": ""971760625"", ""accession"": ""YP_00921388...",NaN,NaN,NaN,NaN,NaN,False,...,52.94,end,"[""ClassifyThermalMetadata"", ""CreateAccessionLi...","{""ClassifyThermalMetadata"": 2.06, ""CreateAcces...",False,literature,explicit,NaN,PMC8307508.1.txt,NaN
476,gemma4:e4b,YP_007675086,Cyanophage P-RSM6,"{""uid"": ""472341570"", ""accession"": ""YP_00767508...",Prochlorococcus NATL2A,Cyanophage,The isolation source is 'Red Sea' and the coor...,NaN,metadata,True,...,419.55999999999995,end,"[""ClassifyThermalMetadata"", ""CreateAccessionLi...","{""ClassifyThermalMetadata"": 2.32, ""CreateAcces...",False,host_literature,inferred,NaN,PMC11724200.1.txt,NaN
688,gemma4:e4b,BCU97102,uncultured marine virus,"{""uid"": ""2033879293"", ""accession"": ""BCU97102"",...",NaN,NaN,NaN,NaN,NaN,False,...,139.14,end,"[""ClassifyThermalMetadata"", ""CreateAccessionLi...","{""ClassifyThermalMetadata"": 2.79, ""CreateAcces...",False,metadata,forced,NaN,NaN,NaN
689,gemma4:e4b,BCU96367,uncultured marine virus,"{""uid"": ""2033878279"", ""accession"": ""BCU96367"",...",NaN,NaN,NaN,NaN,NaN,False,...,138.92999999999998,end,"[""ClassifyThermalMetadata"", ""CreateAccessionLi...","{""ClassifyThermalMetadata"": 2.66, ""CreateAcces...",False,metadata,forced,NaN,NaN,NaN
690,gemma4:e4b,BCU93598,uncultured marine virus,"{""uid"": ""2033875055"", ""accession"": ""BCU93598"",...",NaN,NaN,NaN,NaN,NaN,False,...,136.9,end,"[""ClassifyThermalMetadata"", ""CreateAccessionLi...","{""ClassifyThermalMetadata"": 2.66, ""CreateAcces...",False,metadata,forced,NaN,NaN,NaN
1160,gemma4:e4b,ATV46299,Lake Baikal phage Baikal-20-5m-C28,"{""uid"": ""1276690552"", ""accession"": ""ATV46299"",...",NaN,NaN,NaN,NaN,NaN,False,...,2.95,end,"[""ClassifyThermalMetadata""]","{""ClassifyThermalMetadata"": 2.95}",False,metadata,inferred,NaN,NaN,NaN
1234,gemma4:e4b,AGH26674,Cyanophage P-RSM3,"{""uid"": ""465283305"", ""accession"": ""AGH26674"", ...",Prochlorococcus NATL2A,organism,The isolation source is 'Red Sea' and the coll...,NaN,metadata,True,...,409.15999999999997,end,"[""ClassifyThermalMetadata"", ""CreateAccessionLi...","{""ClassifyThermalMetadata"": 2.75, ""CreateAcces...",False,host_literature,inferred,NaN,PMC11724200.1.txt,NaN

In [26]:
df =pd.read_csv('TMP_results/democratic/democratic_result.csv')
errs=len(df[df['decision']=='ERROR'])
print(f'Number of errors: {errs}')
uniques=df['thermal_range'].unique()
print(f'Unique entries: {uniques}')
df[df['thermal_range']=='psychrophile']

Number of errors: 301
Unique entries: ['mesophile' 'ERROR' 'thermophile' 'psychrophile' 'none']

,model,accession,phage,metadata,host,taxonomic_level,host_reasoning,host_confidence,host_source,host_found,...,nodes,timings,JSONDecodeError,thermal_source,inference_type,host_paper,thermal_paper,thermal_votes,thermal_reasoning_file,error_message
425,gemma4:e4b,YP_009213881,Escherichia phage vB_EcoM_VR26,"{""uid"": ""971760625"", ""accession"": ""YP_00921388...",Escherichia coli,species,The metadata explicitly contains the key 'host...,NaN,metadata,True,...,"[""CreateAccessionLibrary"", ""ClassifyHostMetada...","{""CreateAccessionLibrary"": 11.86, ""ClassifyHos...",False,NaN,NaN,NaN,NaN,"{'thermophile': 0, 'psychrophile': 2, 'mesophi...",TMP_results/accessions/YP_009213881/reasoning/...,NaN
460,gemma4:e4b,YP_009030086,Serratia phage PS2,"{""uid"": ""639438356"", ""accession"": ""YP_00903008...",Serratia marcescens,species,The metadata explicitly states 'host': 'Serrat...,NaN,metadata,True,...,"[""CreateAccessionLibrary"", ""ClassifyHostMetada...","{""CreateAccessionLibrary"": 30.75, ""ClassifyHos...",False,NaN,NaN,NaN,NaN,"{'thermophile': 0, 'psychrophile': 1, 'mesophi...",TMP_results/accessions/YP_009030086/reasoning/...,NaN
537,gemma4:e4b,WAX22921,Synechococcus phage S-M1,"{""uid"": ""2416396990"", ""accession"": ""WAX22921"",...",Synechococcus sp. WH 7803,strain,The metadata explicitly states the 'host' as '...,NaN,metadata,True,...,"[""CreateAccessionLibrary"", ""ClassifyHostMetada...","{""CreateAccessionLibrary"": 3.39, ""ClassifyHost...",False,NaN,NaN,NaN,NaN,"{'thermophile': 0, 'psychrophile': 1, 'mesophi...",TMP_results/accessions/WAX22921/reasoning/reas...,NaN
688,gemma4:e4b,BCU97102,uncultured marine virus,"{""uid"": ""2033879293"", ""accession"": ""BCU97102"",...",NaN,NaN,NaN,NaN,NaN,False,...,"[""CreateAccessionLibrary"", ""ClassifyHostMetada...","{""CreateAccessionLibrary"": 11.4, ""ClassifyHost...",False,NaN,NaN,NaN,NaN,"{'thermophile': 0, 'psychrophile': 1, 'mesophi...",TMP_results/accessions/BCU97102/reasoning/reas...,NaN
689,gemma4:e4b,BCU96367,uncultured marine virus,"{""uid"": ""2033878279"", ""accession"": ""BCU96367"",...",NaN,NaN,NaN,NaN,NaN,False,...,"[""CreateAccessionLibrary"", ""ClassifyHostMetada...","{""CreateAccessionLibrary"": 10.54, ""ClassifyHos...",False,NaN,NaN,NaN,NaN,"{'thermophile': 0, 'psychrophile': 1, 'mesophi...",TMP_results/accessions/BCU96367/reasoning/reas...,NaN
690,gemma4:e4b,BCU93598,uncultured marine virus,"{""uid"": ""2033875055"", ""accession"": ""BCU93598"",...",NaN,NaN,NaN,NaN,NaN,False,...,"[""CreateAccessionLibrary"", ""ClassifyHostMetada...","{""CreateAccessionLibrary"": 11.15, ""ClassifyHos...",False,NaN,NaN,NaN,NaN,"{'thermophile': 0, 'psychrophile': 1, 'mesophi...",TMP_results/accessions/BCU93598/reasoning/reas...,NaN
1149,gemma4:e4b,AXH72831,Caudoviricetes sp.,"{""uid"": ""1436198934"", ""accession"": ""AXH72831"",...",Methylophilaceae,family,"The abstract states: ""Here, we describe a comp...",NaN,literature,True,...,"[""CreateAccessionLibrary"", ""ClassifyHostMetada...","{""CreateAccessionLibrary"": 27.29, ""ClassifyHos...",False,NaN,NaN,PMC13059738.1.txt,NaN,"{'thermophile': 0, 'psychrophile': 1, 'mesophi...",TMP_results/accessions/AXH72831/reasoning/reas...,NaN
1160,gemma4:e4b,ATV46299,Lake Baikal phage Baikal-20-5m-C28,"{""uid"": ""1276690552"", ""accession"": ""ATV46299"",...",Polynucleobacter,genus,"The text states, ""...as well as a phage infect...",NaN,literature,True,...,"[""CreateAccessionLibrary"", ""ClassifyHostMetada...","{""CreateAccessionLibrary"": 3.78, ""ClassifyHost...",False,NaN,NaN,29079621.txt,NaN,"{'thermophile': 0, 'psychrophile': 3, 'mesophi...",TMP_results/accessions/ATV46299/reasoning/reas...,NaN
1234,gemma4:e4b,AGH26674,Cyanophage P-RSM3,"{""uid"": ""465283305"", ""accession"": ""AGH26674"", ...",Prochlorococcus NATL2A,strain,The metadata explicitly contains the key 'lab_...,NaN,metadata,True,...,"[""CreateAccessionLibrary"", ""ClassifyHostMetada...","{""CreateAccessionLibrary"": 22.95, ""ClassifyHos...",False,NaN,NaN,NaN,NaN,"{'thermophile': 0, 'psychrophile': 1, 'mesophi...",TMP_results/accessions/AGH26674/reasoning/reas...,NaN