In [9]:
from src.biotools.fasta_tools import *
seq=ExtractSequence('P04529','../uvsx/data/curated_database/filtered_curated_database.fasta')

In [10]:
walker_a=seq[58:67]
walker_b=seq[137:143]

In [18]:
print(f'Walker A motif: {walker_a}')
print(f'Walker B motif: {walker_b}')

Walker A motif: AGPSKSFKS
Walker B motif: VVVFID

In [12]:
import re
#looking for walker A in the gold standards

files = [
    '../uvsx/data/references/P04529.fasta',
    '../uvsx/data/references/9GBG.fasta',
    '../uvsx/data/references/7Z3M.fasta'
]

results = {}

for file in files:
    seq = read_fasta(file)
    name = file.split('/')[-1].split('.')[0]

    matches = []
    for match in re.finditer(r"[AVILMFWY]{4}DE?", seq):
        matches.append({
            "match": match.group(),
            "start": match.start(),
            "end": match.end()
        })

    results[name] = matches

print(results)

{'P04529': [{'match': 'VVFID', 'start': 138, 'end': 143}], '9GBG': [], '7Z3M': [{'match': 'LFILD', 'start': 156, 'end': 161}]}

In [45]:
import pandas as pd
df=pd.read_csv('../uvsx/data/curated_database/cleaned_metadata.csv')

In [46]:
#Finding Walker A motif in whole database
def MotifDatabaseSearch(accessions, database, regex):
    results={}
    present=[]
    for acc in accessions:
        seq = ExtractSequence(acc, database)

        matches = []
        for match in re.finditer(regex, seq):
            matches.append({
                "match": match.group(),
                "start": match.start(),
                "end": match.end()
            })

        results[acc] = matches
        if len(matches)==0:
            present.append(0)
        else:
            present.append(1)

    return results, present

In [54]:
a_results, a_present=MotifDatabaseSearch(df['accession'], '../uvsx/data/curated_database/cleaned_curated_database.fasta', r"[GA]....[GF]K[TS]")

In [55]:
b_results, b_present=MotifDatabaseSearch(df['accession'], '../uvsx/data/curated_database/cleaned_curated_database.fasta', r"[AVILMFWY]{4}DE?")

In [58]:
sum(b_present)

13007

In [43]:
a_absent=[]

for acc in df['accession']:
    if len(a_results[acc]) == 0:
        a_absent.append(acc)
print(f'Number of Sequences without Walker A: {len(a_absent)}')

a_fs=[]
for acc in df['accession']:
    for match in a_results[acc]:
        seq=match.get('match')
        if seq[-3] == 'F':
            a_fs.append(acc)

print(f'Number of Sequences With F instead of G: {len(a_fs)}')

Number of Sequences without Walker A: 20549
Number of Sequences With F instead of G: 0

In [16]:
# Finding walker B motif
b_results={}
b_present=[]
for acc in df['accession']:
    seq = ExtractSequence(acc, '../uvsx/data/curated_database/cleaned_curated_database.fasta')

    matches = []
    for match in re.finditer(r"[AVILMFWY]{4}DE?", seq):
        matches.append({
            "match": match.group(),
            "start": match.start(),
            "end": match.end()
        })

    b_results[acc] = matches
    if len(matches)==0:
        print(f'{acc} WALKER B NOT FOUND')
        b_present.append(0)
    else:
        b_present.append(1)

P32270 WALKER B NOT FOUND
YDI96965 WALKER B NOT FOUND
YDI96730 WALKER B NOT FOUND
YDF88887 WALKER B NOT FOUND
YDF81549 WALKER B NOT FOUND
YDF75915 WALKER B NOT FOUND
YDF71083 WALKER B NOT FOUND
YDF68759 WALKER B NOT FOUND
YDF68054 WALKER B NOT FOUND
YDF61728 WALKER B NOT FOUND
YCZ41734 WALKER B NOT FOUND
YCQ84975 WALKER B NOT FOUND
O21960 WALKER B NOT FOUND
O21959 WALKER B NOT FOUND
O21958 WALKER B NOT FOUND
O21957 WALKER B NOT FOUND
O21956 WALKER B NOT FOUND
O21955 WALKER B NOT FOUND
O21954 WALKER B NOT FOUND
O21953 WALKER B NOT FOUND
O21952 WALKER B NOT FOUND
O21951 WALKER B NOT FOUND
O21950 WALKER B NOT FOUND
O21949 WALKER B NOT FOUND
O21947 WALKER B NOT FOUND
O21948 WALKER B NOT FOUND
Q06728 WALKER B NOT FOUND
Q06727 WALKER B NOT FOUND
P04537 WALKER B NOT FOUND
P41662 WALKER B NOT FOUND
YCJ24104 WALKER B NOT FOUND
XSD99949 WALKER B NOT FOUND
UNA07219 WALKER B NOT FOUND
UMO75314 WALKER B NOT FOUND
YBX93090 WALKER B NOT FOUND
YBX92995 WALKER B NOT FOUND
YBX92994 WALKER B NOT FOUND
YBX92932 WALKER B NOT FOUND
XHQ01490 WALKER B NOT FOUND
CAO2920117 WALKER B NOT FOUND
YBB95625 WALKER B NOT FOUND
YAS76301 WALKER B NOT FOUND
XYY30183 WALKER B NOT FOUND
XYM49803 WALKER B NOT FOUND
XYL46262 WALKER B NOT FOUND
XYL33160 WALKER B NOT FOUND
XYL02172 WALKER B NOT FOUND
XYH91864 WALKER B NOT FOUND
XXJ49601 WALKER B NOT FOUND
XWX36420 WALKER B NOT FOUND
XWX33057 WALKER B NOT FOUND
XAI97619 WALKER B NOT FOUND
XTB82809 WALKER B NOT FOUND
QXP07734 WALKER B NOT FOUND
XQQ56485 WALKER B NOT FOUND
XPQ48074 WALKER B NOT FOUND
XPP56688 WALKER B NOT FOUND
XPP61562 WALKER B NOT FOUND
XPP61528 WALKER B NOT FOUND
CAM0087880 WALKER B NOT FOUND
CAM0086762 WALKER B NOT FOUND
CAM0086726 WALKER B NOT FOUND
CAM0070331 WALKER B NOT FOUND
CAL9965632 WALKER B NOT FOUND
CAL9959071 WALKER B NOT FOUND
CAL9958490 WALKER B NOT FOUND
CAL9958463 WALKER B NOT FOUND
XOT40235 WALKER B NOT FOUND
XJP46991 WALKER B NOT FOUND
XOS73725 WALKER B NOT FOUND
XOS72248 WALKER B NOT FOUND
XOS71006 WALKER B NOT FOUND
XOS69093 WALKER B NOT FOUND
XOS67356 WALKER B NOT FOUND
XOS67041 WALKER B NOT FOUND
XOS67020 WALKER B NOT FOUND
XOS66747 WALKER B NOT FOUND
XOS66738 WALKER B NOT FOUND
XOS65941 WALKER B NOT FOUND
XOS65370 WALKER B NOT FOUND
XOS63655 WALKER B NOT FOUND
XOS63260 WALKER B NOT FOUND
XOS63005 WALKER B NOT FOUND
XOS61786 WALKER B NOT FOUND
XOS60468 WALKER B NOT FOUND
XOS59345 WALKER B NOT FOUND
XOS56450 WALKER B NOT FOUND
XOS55399 WALKER B NOT FOUND
XOS54634 WALKER B NOT FOUND
XOS52812 WALKER B NOT FOUND
XOS51285 WALKER B NOT FOUND
XOS49849 WALKER B NOT FOUND
XOS47258 WALKER B NOT FOUND
XOS46627 WALKER B NOT FOUND
XOS46481 WALKER B NOT FOUND
XOS45357 WALKER B NOT FOUND
XOS44562 WALKER B NOT FOUND
XOS41541 WALKER B NOT FOUND
XOS41138 WALKER B NOT FOUND
XOS40969 WALKER B NOT FOUND
XOS36958 WALKER B NOT FOUND
XOS35688 WALKER B NOT FOUND
XOS33684 WALKER B NOT FOUND
XOS25815 WALKER B NOT FOUND
XOS24228 WALKER B NOT FOUND
XOS22228 WALKER B NOT FOUND
XOS21353 WALKER B NOT FOUND
XOS21150 WALKER B NOT FOUND
XOS20052 WALKER B NOT FOUND
XOS17920 WALKER B NOT FOUND
XOS17677 WALKER B NOT FOUND
XOS17631 WALKER B NOT FOUND
XOS07809 WALKER B NOT FOUND
XOS02778 WALKER B NOT FOUND
XOS02326 WALKER B NOT FOUND
XOS02234 WALKER B NOT FOUND
XOS01833 WALKER B NOT FOUND
XOS01144 WALKER B NOT FOUND
XOS00534 WALKER B NOT FOUND
XOS00257 WALKER B NOT FOUND
XOR98083 WALKER B NOT FOUND
XOR97908 WALKER B NOT FOUND
XOR97684 WALKER B NOT FOUND
XOR97311 WALKER B NOT FOUND
XOR95897 WALKER B NOT FOUND
XOR95616 WALKER B NOT FOUND
XOR93566 WALKER B NOT FOUND
XOR92952 WALKER B NOT FOUND
XOR91955 WALKER B NOT FOUND
XOR91179 WALKER B NOT FOUND
XOR91056 WALKER B NOT FOUND
XOR90744 WALKER B NOT FOUND
XOR90310 WALKER B NOT FOUND
XOR88738 WALKER B NOT FOUND
XOR85920 WALKER B NOT FOUND
XOR85339 WALKER B NOT FOUND
XOR85023 WALKER B NOT FOUND
XOR84192 WALKER B NOT FOUND
XOR82736 WALKER B NOT FOUND
XOR78396 WALKER B NOT FOUND
XOR78082 WALKER B NOT FOUND
XOR75323 WALKER B NOT FOUND
XOR73130 WALKER B NOT FOUND
XOR69809 WALKER B NOT FOUND
XOR69773 WALKER B NOT FOUND
XOR69130 WALKER B NOT FOUND
XOR68555 WALKER B NOT FOUND
XOR68253 WALKER B NOT FOUND
XOR65995 WALKER B NOT FOUND
XOR63545 WALKER B NOT FOUND
XOR63187 WALKER B NOT FOUND
XOR59935 WALKER B NOT FOUND
XOR55866 WALKER B NOT FOUND
XOR53510 WALKER B NOT FOUND
XOR52513 WALKER B NOT FOUND
XOR51467 WALKER B NOT FOUND
XOR51313 WALKER B NOT FOUND
XOR51251 WALKER B NOT FOUND
XOR51057 WALKER B NOT FOUND
XOR51028 WALKER B NOT FOUND
XOR47264 WALKER B NOT FOUND
XOR47031 WALKER B NOT FOUND
XOR44972 WALKER B NOT FOUND
XOR44808 WALKER B NOT FOUND
XOR43780 WALKER B NOT FOUND
XOR43550 WALKER B NOT FOUND
XOR42631 WALKER B NOT FOUND
XOR42147 WALKER B NOT FOUND
XOR40197 WALKER B NOT FOUND
XOR39440 WALKER B NOT FOUND
XOR39236 WALKER B NOT FOUND
XOR36053 WALKER B NOT FOUND
XOR35770 WALKER B NOT FOUND
XOR35443 WALKER B NOT FOUND
XOR34618 WALKER B NOT FOUND
XOR33923 WALKER B NOT FOUND
XOR33708 WALKER B NOT FOUND
XOR32002 WALKER B NOT FOUND
XOR28202 WALKER B NOT FOUND
XOR25079 WALKER B NOT FOUND
XOR24806 WALKER B NOT FOUND
XOR24766 WALKER B NOT FOUND
XOR24180 WALKER B NOT FOUND
XOR24157 WALKER B NOT FOUND
XOR23623 WALKER B NOT FOUND
XOR22859 WALKER B NOT FOUND
XOR22232 WALKER B NOT FOUND
XOR19608 WALKER B NOT FOUND
XOR18454 WALKER B NOT FOUND
XOR17395 WALKER B NOT FOUND
XOR12226 WALKER B NOT FOUND
XOR09288 WALKER B NOT FOUND
XOR09003 WALKER B NOT FOUND
XOR08563 WALKER B NOT FOUND
XOR07990 WALKER B NOT FOUND
XOR06429 WALKER B NOT FOUND
XOR06060 WALKER B NOT FOUND
XOR01881 WALKER B NOT FOUND
XOR01253 WALKER B NOT FOUND
XOQ98299 WALKER B NOT FOUND
XOQ93077 WALKER B NOT FOUND
XOQ91860 WALKER B NOT FOUND
XOQ91551 WALKER B NOT FOUND
XOQ90170 WALKER B NOT FOUND
XOQ89917 WALKER B NOT FOUND
XOQ89880 WALKER B NOT FOUND
XOQ88760 WALKER B NOT FOUND
XOQ88539 WALKER B NOT FOUND
XOQ87717 WALKER B NOT FOUND
XOQ87433 WALKER B NOT FOUND
QYC50815 WALKER B NOT FOUND
XOD32956 WALKER B NOT FOUND
P35926 WALKER B NOT FOUND
P04892 WALKER B NOT FOUND
XNT20930 WALKER B NOT FOUND
XNS38718 WALKER B NOT FOUND
XNS38713 WALKER B NOT FOUND
XNS38344 WALKER B NOT FOUND
XNS37986 WALKER B NOT FOUND
XNS37968 WALKER B NOT FOUND
XNS37669 WALKER B NOT FOUND
XNS37337 WALKER B NOT FOUND
WAE39405 WALKER B NOT FOUND
ALJ98503 WALKER B NOT FOUND
XLM28285 WALKER B NOT FOUND
XLM27629 WALKER B NOT FOUND
XLM27356 WALKER B NOT FOUND
XLM27243 WALKER B NOT FOUND
XLL21201 WALKER B NOT FOUND
XLL20700 WALKER B NOT FOUND
XLL20648 WALKER B NOT FOUND
XLG25413 WALKER B NOT FOUND
XLG23789 WALKER B NOT FOUND
XKC20595 WALKER B NOT FOUND
XIU00024 WALKER B NOT FOUND
XII43063 WALKER B NOT FOUND
XHV14808 WALKER B NOT FOUND
XHH73842 WALKER B NOT FOUND
XHH73317 WALKER B NOT FOUND
XHB26724 WALKER B NOT FOUND
XGU08019 WALKER B NOT FOUND
XGU07500 WALKER B NOT FOUND
XGU06302 WALKER B NOT FOUND
WPH65344 WALKER B NOT FOUND
XEN18361 WALKER B NOT FOUND
XDJ02632 WALKER B NOT FOUND
XDI97733 WALKER B NOT FOUND
XDI97023 WALKER B NOT FOUND
XDI97022 WALKER B NOT FOUND
XDI96518 WALKER B NOT FOUND
XDI97897 WALKER B NOT FOUND
WAK43740 WALKER B NOT FOUND
XCN28352 WALKER B NOT FOUND
WDQ45472 WALKER B NOT FOUND
XCI68037 WALKER B NOT FOUND
XCI67732 WALKER B NOT FOUND
XCI67158 WALKER B NOT FOUND
XCD05073 WALKER B NOT FOUND
BFM94432 WALKER B NOT FOUND
BFM94189 WALKER B NOT FOUND
BFM93886 WALKER B NOT FOUND
BFM93642 WALKER B NOT FOUND
BFM93338 WALKER B NOT FOUND
XAO34940 WALKER B NOT FOUND
WVX91621 WALKER B NOT FOUND
XAI96809 WALKER B NOT FOUND
XAI95602 WALKER B NOT FOUND
XAG93834 WALKER B NOT FOUND
WZB39575 WALKER B NOT FOUND
WYN33742 WALKER B NOT FOUND
WYD63227 WALKER B NOT FOUND
WXX03052 WALKER B NOT FOUND
WWT40039 WALKER B NOT FOUND
WWQ72209 WALKER B NOT FOUND
WWQ71916 WALKER B NOT FOUND
WPK41687 WALKER B NOT FOUND
WPK41462 WALKER B NOT FOUND
WPK41295 WALKER B NOT FOUND
WPK41084 WALKER B NOT FOUND
CAK9121845 WALKER B NOT FOUND
CAK9121839 WALKER B NOT FOUND
WVX93361 WALKER B NOT FOUND
WVX93288 WALKER B NOT FOUND
WVX93220 WALKER B NOT FOUND
WVX88151 WALKER B NOT FOUND
WVR18332 WALKER B NOT FOUND
WIT26513 WALKER B NOT FOUND
WQN07582 WALKER B NOT FOUND
WPH67316 WALKER B NOT FOUND
WPH58923 WALKER B NOT FOUND
WPH58212 WALKER B NOT FOUND
BEU75324 WALKER B NOT FOUND
BEU75322 WALKER B NOT FOUND
WPD58321 WALKER B NOT FOUND
WNM51361 WALKER B NOT FOUND
WNM51357 WALKER B NOT FOUND
WNM51104 WALKER B NOT FOUND
WNM51101 WALKER B NOT FOUND
WNM50664 WALKER B NOT FOUND
WNM50662 WALKER B NOT FOUND
WNM50416 WALKER B NOT FOUND
P14819 WALKER B NOT FOUND
WNV45487 WALKER B NOT FOUND
WNN95444 WALKER B NOT FOUND
WNL49442 WALKER B NOT FOUND
QWM90999 WALKER B NOT FOUND
QWM90716 WALKER B NOT FOUND
QWM91441 WALKER B NOT FOUND
QWM91339 WALKER B NOT FOUND
QWM91259 WALKER B NOT FOUND
QWM91030 WALKER B NOT FOUND
QWM90888 WALKER B NOT FOUND
QWM90798 WALKER B NOT FOUND
QOR60026 WALKER B NOT FOUND
QOR59977 WALKER B NOT FOUND
QOR57907 WALKER B NOT FOUND
QOR57844 WALKER B NOT FOUND
QOR57759 WALKER B NOT FOUND
QOR57617 WALKER B NOT FOUND
QOR57563 WALKER B NOT FOUND
QOR57445 WALKER B NOT FOUND
QOR57415 WALKER B NOT FOUND
QOR57314 WALKER B NOT FOUND
QOR57189 WALKER B NOT FOUND
QOR57171 WALKER B NOT FOUND
QOR57019 WALKER B NOT FOUND
QOR56939 WALKER B NOT FOUND
QOR56874 WALKER B NOT FOUND
QOR56737 WALKER B NOT FOUND
QOR56714 WALKER B NOT FOUND
CAJ1887602 WALKER B NOT FOUND
CAJ1762137 WALKER B NOT FOUND
WDS51879 WALKER B NOT FOUND
UVK64370 WALKER B NOT FOUND
UVK64283 WALKER B NOT FOUND
UTN91884 WALKER B NOT FOUND
QJD49850 WALKER B NOT FOUND
QGJ97116 WALKER B NOT FOUND
QGH75405 WALKER B NOT FOUND
QFG07946 WALKER B NOT FOUND
QDK03146 WALKER B NOT FOUND
AXH49442 WALKER B NOT FOUND
AXC35923 WALKER B NOT FOUND
AXC33336 WALKER B NOT FOUND
AWY07537 WALKER B NOT FOUND
AWY07455 WALKER B NOT FOUND
AWN05266 WALKER B NOT FOUND
AVR77016 WALKER B NOT FOUND
ATW60933 WALKER B NOT FOUND
AQY55733 WALKER B NOT FOUND
AQY55651 WALKER B NOT FOUND
ALH46913 WALKER B NOT FOUND
AGK87803 WALKER B NOT FOUND
AFN37670 WALKER B NOT FOUND
AEJ93540 WALKER B NOT FOUND
AEJ93450 WALKER B NOT FOUND
UUG68540 WALKER B NOT FOUND
BAF36098 WALKER B NOT FOUND
WLJ26246 WALKER B NOT FOUND
WLJ25866 WALKER B NOT FOUND
WLJ25823 WALKER B NOT FOUND
WLJ25709 WALKER B NOT FOUND
WLJ25679 WALKER B NOT FOUND
WKW86767 WALKER B NOT FOUND
UIS65459 WALKER B NOT FOUND
WIC89204 WALKER B NOT FOUND
WJZ48734 WALKER B NOT FOUND
DBA08604 WALKER B NOT FOUND
WBF77874 WALKER B NOT FOUND
CAI9752491 WALKER B NOT FOUND
WHM49643 WALKER B NOT FOUND
YP_009782850 WALKER B NOT FOUND
YP_009782660 WALKER B NOT FOUND
YP_009782420 WALKER B NOT FOUND
YP_009782175 WALKER B NOT FOUND
YP_009098288 WALKER B NOT FOUND
UPT53388 WALKER B NOT FOUND
UPT53089 WALKER B NOT FOUND
YP_010773168 WALKER B NOT FOUND
YP_010771377 WALKER B NOT FOUND
YP_010771346 WALKER B NOT FOUND
YP_010765968 WALKER B NOT FOUND
YP_010765901 WALKER B NOT FOUND
YP_010765836 WALKER B NOT FOUND
YP_010765824 WALKER B NOT FOUND
YP_010765737 WALKER B NOT FOUND
YP_010749648 WALKER B NOT FOUND
YP_010667622 WALKER B NOT FOUND
WFG54154 WALKER B NOT FOUND
WFG33786 WALKER B NOT FOUND
YP_010748823 WALKER B NOT FOUND
YP_010748766 WALKER B NOT FOUND
YP_010748710 WALKER B NOT FOUND
YP_010747975 WALKER B NOT FOUND
YP_010747791 WALKER B NOT FOUND
YP_010747724 WALKER B NOT FOUND
YP_010746437 WALKER B NOT FOUND
YP_010746071 WALKER B NOT FOUND
YP_010746011 WALKER B NOT FOUND
YP_010745950 WALKER B NOT FOUND
YP_010745885 WALKER B NOT FOUND
CAI3971366 WALKER B NOT FOUND
WEU70066 WALKER B NOT FOUND
YP_010719912 WALKER B NOT FOUND
YP_010719508 WALKER B NOT FOUND
WDQ27557 WALKER B NOT FOUND
BCV00617 WALKER B NOT FOUND
YP_010680492 WALKER B NOT FOUND
YP_010664096 WALKER B NOT FOUND
YP_010664016 WALKER B NOT FOUND
YP_010649883 WALKER B NOT FOUND
YP_010648468 WALKER B NOT FOUND
YP_010597585 WALKER B NOT FOUND
YP_010597534 WALKER B NOT FOUND
YP_010597435 WALKER B NOT FOUND
UKH47761 WALKER B NOT FOUND
UWI39023 WALKER B NOT FOUND
UWI36222 WALKER B NOT FOUND
UWI32924 WALKER B NOT FOUND
UWI30777 WALKER B NOT FOUND
UWI30218 WALKER B NOT FOUND
UWI29128 WALKER B NOT FOUND
UWI22452 WALKER B NOT FOUND
UWI22275 WALKER B NOT FOUND
UWI20821 WALKER B NOT FOUND
UWI17490 WALKER B NOT FOUND
UWI13810 WALKER B NOT FOUND
UWI11317 WALKER B NOT FOUND
UWI09616 WALKER B NOT FOUND
UWI08952 WALKER B NOT FOUND
UWI07957 WALKER B NOT FOUND
UWI01811 WALKER B NOT FOUND
UWH99798 WALKER B NOT FOUND
UWH97961 WALKER B NOT FOUND
UWG93489 WALKER B NOT FOUND
UWG92036 WALKER B NOT FOUND
UWG89589 WALKER B NOT FOUND
UWG87425 WALKER B NOT FOUND
UWG84062 WALKER B NOT FOUND
UWG78450 WALKER B NOT FOUND
UWG74909 WALKER B NOT FOUND
UWG74758 WALKER B NOT FOUND
UWG69745 WALKER B NOT FOUND
UWD77355 WALKER B NOT FOUND
UWD74511 WALKER B NOT FOUND
UWD73542 WALKER B NOT FOUND
UWD72265 WALKER B NOT FOUND
UWD71629 WALKER B NOT FOUND
UWD71068 WALKER B NOT FOUND
UWD68852 WALKER B NOT FOUND
UWD65541 WALKER B NOT FOUND
UWD59959 WALKER B NOT FOUND
UWD58912 WALKER B NOT FOUND
UWD54686 WALKER B NOT FOUND
UWD51995 WALKER B NOT FOUND
UVD39726 WALKER B NOT FOUND
YP_010358677 WALKER B NOT FOUND
YP_010509939 WALKER B NOT FOUND
YP_010509656 WALKER B NOT FOUND
YP_010509570 WALKER B NOT FOUND
YP_010298979 WALKER B NOT FOUND
YP_010110145 WALKER B NOT FOUND
YP_010050273 WALKER B NOT FOUND
YP_010049900 WALKER B NOT FOUND
YP_009986978 WALKER B NOT FOUND
YP_009949207 WALKER B NOT FOUND
YP_009909734 WALKER B NOT FOUND
YP_009883330 WALKER B NOT FOUND
YP_009859606 WALKER B NOT FOUND
YP_009777881 WALKER B NOT FOUND
YP_009777614 WALKER B NOT FOUND
YP_009638929 WALKER B NOT FOUND
YP_007236364 WALKER B NOT FOUND
YP_007005559 WALKER B NOT FOUND
YP_006201134 WALKER B NOT FOUND
YP_002302518 WALKER B NOT FOUND
YP_001686773 WALKER B NOT FOUND
YP_803126 WALKER B NOT FOUND
YP_240570 WALKER B NOT FOUND
YP_240112 WALKER B NOT FOUND
YP_240035 WALKER B NOT FOUND
YP_239205 WALKER B NOT FOUND
YP_164276 WALKER B NOT FOUND
NP_958095 WALKER B NOT FOUND
NP_944133 WALKER B NOT FOUND
NP_720299 WALKER B NOT FOUND
NP_620347 WALKER B NOT FOUND
NP_049799 WALKER B NOT FOUND
NP_052293 WALKER B NOT FOUND
NP_052292 WALKER B NOT FOUND
NP_052291 WALKER B NOT FOUND
NP_052290 WALKER B NOT FOUND
YP_010101504 WALKER B NOT FOUND
YP_010092771 WALKER B NOT FOUND
YP_010091903 WALKER B NOT FOUND
YP_010083203 WALKER B NOT FOUND
YP_010082193 WALKER B NOT FOUND
YP_010054218 WALKER B NOT FOUND
YP_010053163 WALKER B NOT FOUND
YP_010053051 WALKER B NOT FOUND
YP_010050516 WALKER B NOT FOUND
YP_010050455 WALKER B NOT FOUND
YP_010050086 WALKER B NOT FOUND
YP_009903627 WALKER B NOT FOUND
YP_009882705 WALKER B NOT FOUND
YP_009882682 WALKER B NOT FOUND
YP_009882609 WALKER B NOT FOUND
YP_009882501 WALKER B NOT FOUND
YP_009882469 WALKER B NOT FOUND
YP_009838939 WALKER B NOT FOUND
YP_009838799 WALKER B NOT FOUND
YP_009838728 WALKER B NOT FOUND
YP_009838667 WALKER B NOT FOUND
YP_009836508 WALKER B NOT FOUND
YP_009836438 WALKER B NOT FOUND
YP_009836096 WALKER B NOT FOUND
YP_009833757 WALKER B NOT FOUND
YP_009821878 WALKER B NOT FOUND
YP_009821242 WALKER B NOT FOUND
YP_009799994 WALKER B NOT FOUND
YP_009799575 WALKER B NOT FOUND
YP_009799355 WALKER B NOT FOUND
YP_009797259 WALKER B NOT FOUND
YP_009621891 WALKER B NOT FOUND
YP_009620130 WALKER B NOT FOUND
YP_009611521 WALKER B NOT FOUND
YP_009611294 WALKER B NOT FOUND
YP_010050396 WALKER B NOT FOUND
YP_010050027 WALKER B NOT FOUND
YP_009914764 WALKER B NOT FOUND
YP_009876148 WALKER B NOT FOUND
YP_009831805 WALKER B NOT FOUND
YP_009842096 WALKER B NOT FOUND
YP_009790873 WALKER B NOT FOUND
YP_009609077 WALKER B NOT FOUND
YP_009606258 WALKER B NOT FOUND
YP_009605937 WALKER B NOT FOUND
YP_009605617 WALKER B NOT FOUND
YP_009605298 WALKER B NOT FOUND
YP_009598752 WALKER B NOT FOUND
YP_009293526 WALKER B NOT FOUND
YP_009285859 WALKER B NOT FOUND
YP_009281134 WALKER B NOT FOUND
YP_009279682 WALKER B NOT FOUND
WBF77103 WALKER B NOT FOUND
YP_010083340 WALKER B NOT FOUND
YP_010082377 WALKER B NOT FOUND
YP_010082286 WALKER B NOT FOUND
YP_010066840 WALKER B NOT FOUND
YP_010066379 WALKER B NOT FOUND
YP_010065982 WALKER B NOT FOUND
YP_009909190 WALKER B NOT FOUND
YP_009806443 WALKER B NOT FOUND
YP_009785190 WALKER B NOT FOUND
YP_009624854 WALKER B NOT FOUND
YP_009613880 WALKER B NOT FOUND
YP_009603600 WALKER B NOT FOUND
YP_009593439 WALKER B NOT FOUND
YP_009352312 WALKER B NOT FOUND
YP_009275845 WALKER B NOT FOUND
YP_009221490 WALKER B NOT FOUND
YP_009219655 WALKER B NOT FOUND
YP_009217894 WALKER B NOT FOUND
YP_009217254 WALKER B NOT FOUND
YP_009214528 WALKER B NOT FOUND
YP_009205628 WALKER B NOT FOUND
YP_009203232 WALKER B NOT FOUND
YP_009200575 WALKER B NOT FOUND
YP_009196167 WALKER B NOT FOUND
YP_009191660 WALKER B NOT FOUND
YP_009191490 WALKER B NOT FOUND
YP_009167750 WALKER B NOT FOUND
YP_009100492 WALKER B NOT FOUND
YP_009004677 WALKER B NOT FOUND
YP_009010227 WALKER B NOT FOUND
YP_009003214 WALKER B NOT FOUND
YP_008770114 WALKER B NOT FOUND
YP_008433301 WALKER B NOT FOUND
YP_008320370 WALKER B NOT FOUND
YP_008318395 WALKER B NOT FOUND
YP_008239761 WALKER B NOT FOUND
YP_008130262 WALKER B NOT FOUND
YP_006907071 WALKER B NOT FOUND
YP_007877677 WALKER B NOT FOUND
YP_007877450 WALKER B NOT FOUND
YP_007111421 WALKER B NOT FOUND
YP_007111398 WALKER B NOT FOUND
YP_007112522 WALKER B NOT FOUND
YP_007112443 WALKER B NOT FOUND
YP_007112441 WALKER B NOT FOUND
YP_007112349 WALKER B NOT FOUND
YP_007112095 WALKER B NOT FOUND
YP_007111729 WALKER B NOT FOUND
YP_007111509 WALKER B NOT FOUND
YP_007011028 WALKER B NOT FOUND
YP_007003506 WALKER B NOT FOUND
YP_007001669 WALKER B NOT FOUND
YP_006382489 WALKER B NOT FOUND
YP_005087313 WALKER B NOT FOUND
YP_004958173 WALKER B NOT FOUND
YP_004324287 WALKER B NOT FOUND
YP_004323792 WALKER B NOT FOUND
YP_004323321 WALKER B NOT FOUND
YP_004250979 WALKER B NOT FOUND
YP_003580063 WALKER B NOT FOUND
YP_002455814 WALKER B NOT FOUND
YP_002333582 WALKER B NOT FOUND
YP_002274210 WALKER B NOT FOUND
YP_002267976 WALKER B NOT FOUND
YP_001956960 WALKER B NOT FOUND
YP_001449322 WALKER B NOT FOUND
YP_001272543 WALKER B NOT FOUND
YP_516211 WALKER B NOT FOUND
YP_239823 WALKER B NOT FOUND
YP_224104 WALKER B NOT FOUND
YP_006602 WALKER B NOT FOUND
NP_943752 WALKER B NOT FOUND
NP_892101 WALKER B NOT FOUND
NP_758899 WALKER B NOT FOUND
NP_543063 WALKER B NOT FOUND
YP_010067068 WALKER B NOT FOUND
YP_009914482 WALKER B NOT FOUND
YP_007947952 WALKER B NOT FOUND
NP_203431 WALKER B NOT FOUND
NP_077580 WALKER B NOT FOUND
WAX24330 WALKER B NOT FOUND
WAX23782 WALKER B NOT FOUND
WAX05191 WALKER B NOT FOUND
WAX05088 WALKER B NOT FOUND
WAK44955 WALKER B NOT FOUND
WAA19696 WALKER B NOT FOUND
UZZ63822 WALKER B NOT FOUND
URE76711 WALKER B NOT FOUND
UUV46826 WALKER B NOT FOUND
UUV46305 WALKER B NOT FOUND
QOC54156 WALKER B NOT FOUND
UYL93721 WALKER B NOT FOUND
UYL93381 WALKER B NOT FOUND
UYL93305 WALKER B NOT FOUND
UYL93227 WALKER B NOT FOUND
UYL87442 WALKER B NOT FOUND
UYL83195 WALKER B NOT FOUND
UYA98908 WALKER B NOT FOUND
UXQ90474 WALKER B NOT FOUND
UXQ89123 WALKER B NOT FOUND
UXE02909 WALKER B NOT FOUND
UWV20396 WALKER B NOT FOUND
UWG27813 WALKER B NOT FOUND
UWG26830 WALKER B NOT FOUND
UWG17071 WALKER B NOT FOUND
UWG14628 WALKER B NOT FOUND
UWG14228 WALKER B NOT FOUND
UWG10212 WALKER B NOT FOUND
UWG06620 WALKER B NOT FOUND
UWG02034 WALKER B NOT FOUND
UWG01351 WALKER B NOT FOUND
UWF95454 WALKER B NOT FOUND
UWF90498 WALKER B NOT FOUND
UWF86991 WALKER B NOT FOUND
UWF84999 WALKER B NOT FOUND
UVX31198 WALKER B NOT FOUND
UVY68666 WALKER B NOT FOUND
UVY67291 WALKER B NOT FOUND
UVY66940 WALKER B NOT FOUND
UVY66610 WALKER B NOT FOUND
UVY66437 WALKER B NOT FOUND
UVY65071 WALKER B NOT FOUND
UVY64690 WALKER B NOT FOUND
UVY64625 WALKER B NOT FOUND
UVY64073 WALKER B NOT FOUND
UVY63513 WALKER B NOT FOUND
UVY61144 WALKER B NOT FOUND
UVY57885 WALKER B NOT FOUND
UVY56183 WALKER B NOT FOUND
UVY55075 WALKER B NOT FOUND
UVY54260 WALKER B NOT FOUND
UVY53938 WALKER B NOT FOUND
UVY52011 WALKER B NOT FOUND
UVY46972 WALKER B NOT FOUND
UVY20493 WALKER B NOT FOUND
UVY19332 WALKER B NOT FOUND
UVY17748 WALKER B NOT FOUND
UVY15741 WALKER B NOT FOUND
UVY14207 WALKER B NOT FOUND
UVY12648 WALKER B NOT FOUND
UVY08722 WALKER B NOT FOUND
UVY05347 WALKER B NOT FOUND
UVY00272 WALKER B NOT FOUND

In [19]:
absent=[]
for acc in df['accession']:
    if len(results[acc]) == 0:
        absent.append(acc)
print(f'Number of Sequences without Walker B: {len(absent)}')

KeyError: 'P32270'

In [20]:
import pandas as pd
hits=pd.read_csv('../uvsx/data/hmms/results/accession_hits.csv')

In [23]:
hits

,accession,full_sequence_hmm_results,PF00154_custom_hmm_results,PF00154_hmm_results,PF21134_custom_hmm_results,PF21134_hmm_results,walker_a,walker_b
0,P32270,0,0,0,0,0,1,0
1,P20315,0,0,0,0,0,0,1
2,UYE93698,0,0,0,0,0,0,1
3,YDI96965,0,0,1,0,0,0,0
4,YDI96730,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...
20544,Q37876,0,0,0,0,0,0,0
20545,Q37877,0,0,0,0,0,0,1
20546,C9DGL1,0,0,0,0,0,0,1
20547,Q9T0S5,0,0,0,0,0,0,0
20548,Q859M4,0,0,0,0,0,0,0

In [61]:
def WriteScoringtoCSV(score_csv, score_vector, score_name):
    df = pd.read_csv(score_csv)
    df[score_name]=score_vector
    df.to_csv(score_csv, index=False)

In [ ]:
WriteScoringtoCSV('../')

In [22]:
top_hits=[]
for index, row in hits.iterrows():
    if sum(row.drop('accession')) == 7:
        top_hits.append(row['accession'])

In [24]:
hits[hits['accession']=='YDI88709']

,accession,full_sequence_hmm_results,PF00154_custom_hmm_results,PF00154_hmm_results,PF21134_custom_hmm_results,PF21134_hmm_results,walker_a,walker_b
8,YDI88709,1,1,1,1,1,1,1

In [25]:
ExtractSequence('YDI88709', '../uvsx/data/curated_database/cleaned_curated_database.fasta')

'MSDLKSRLIKASTSKMTADLTKSKLFNNRDEVPTRIPMLNIALGGALNAGLQSGLTIFAAPSKHFKTLFGLTMVAAYMKKYKDAICLFYDSEFGASESYFRSMGVDLDRVVHTPIQSVEQLKVDMTNQLDAIERGDKVIIFIDSIGNTASKKETEDALNEKVVGDMSRAKALKSLFRIVTPYLTIKDIPCVAINHTAMEIGGLYPKEIMGGGTGILYSANTVFFISKRQVKEGTELTGYDFTLKAEKSRTVKEKSTFPITVNFDGGIDPFSGLLEMATEIGFVVKPKAGWYAREFLDEETGEMIREEKSWRAKATDCVEFWGPLFKHKPFRDAIETKYKLGAISSIKEVDDAVNDLINCKATTKVPVKTSDAPSAADIENDLDEMEDFDE'

In [26]:
ExtractSequence('P04529', '../uvsx/data/curated_database/cleaned_curated_database.fasta')

'MSDLKSRLIKASTSKLTAELTASKFFNEKDVVRTKIPMMNIALSGEITGGMQSGLLILAGPSKSFKSNFGLTMVSSYMRQYPDAVCLFYDSEFGITPAYLRSMGVDPERVIHTPVQSLEQLRIDMVNQLDAIERGEKVVVFIDSLGNLASKKETEDALNEKVVSDMTRAKTMKSLFRIVTPYFSTKNIPCIAINHTYETQEMFSKTVMGGGTGPMYSADTVFIIGKRQIKDGSDLQGYQFVLNVEKSRTVKEKSKFFIDVKFDGGIDPYSGLLDMALELGFVVKPKNGWYAREFLDEETGEMIREEKSWRAKDTNCTTFWGPLFKHQPFRDAIKRAYQLGAIDSNEIVEAEVDELINSKVEKFKSPESKSKSAADLETDLEQLSDMEEFNE'

In [27]:
len(top_hits)

626

In [28]:
for acc in top_hits:
    seq=ExtractSequence(acc, '../uvsx/data/curated_database/cleaned_curated_database.fasta')
    if len(seq) < 300 and len(seq) > 400:
        print(f'{acc} has abbererant sequence\n{seq}')

Okay so 626 sequences have a hit for all 7 checks. However with walker a and b these hits may be in sections of the protein that dont make sense
Potentially need to do filtering for motif hits that are in sketchy locations

In [33]:
#Rational design paper has loops 1 and 2
seq=ExtractSequence('P04529', '../uvsx/data/curated_database/cleaned_curated_database.fasta')
ploop=seq[58:67]
loop1=seq[151:165]
loop2=seq[197:211]
print(f'Loop 1: {loop1}')
print(f'Loop 2: {loop2}')

Loop 1: KETEDALNEKVVSD
Loop 2: ETQEMFSKTVMGGG